<?php
$industries =
	["accommodation"
	,"food services"
	,"administrative"
	,"support services"
	,"administrative"
	,"support"
	,"waste management"
	,"remediation services"
	,"agriculture"
	,"forestry"
	,"fishing"
	,"hunting"
	,"air transportation"
	,"ambulatory health care services"
	,"amusement"
	,"gambling"
	,"recreation industries"
	,"animal production"
	,"apparel manufacturing"
	,"arts"
	,"entertainment"
	,"recreation"
	,"beverage"
	,"tobacco product manufacturing"
	,"broadcasting (except internet)"
	,"building material"
	,"garden equipment"
	,"supplies dealers"
	,"chemical manufacturing"
	,"clothing"
	,"clothing accessories stores"
	,"computer"
	,"electronic product manufacturing"
	,"construction"
	,"construction of buildings"
	,"couriers"
	,"messengers"
	,"credit intermediation"
	,"related activities"
	,"crop production"
	,"data processing"
	,"hosting"
	,"related services"
	,"education"
	,"health services"
	,"educational services"
	,"electrical equipment"
	,"appliance"
	,"component manufacturing"
	,"electronics"
	,"appliance stores"
	,"fabricated metal product manufacturing"
	,"finance"
	,"insurance"
	,"financial activities"
	,"fishing"
	,"hunting"
	,"trapping"
	,"food manufacturing"
	,"food services"
	,"drinking places"
	,"food"
	,"beverage stores"
	,"forestry"
	,"logging"
	,"funds"
	,"trusts"
	,"other financial vehicles"
	,"furniture"
	,"home furnishings stores"
	,"furniture"
	,"related product manufacturing"
	,"gasoline stations"
	,"general merchandise stores"
	,"goods-producing industries"
	,"health care"
	,"social assistance"
	,"health"
	,"personal care stores"
	,"heavy"
	,"civil engineering construction"
	,"hospitals"
	,"information"
	,"insurance carriers"
	,"related activities"
	,"internet publishing"
	,"broadcasting"
	,"leather"
	,"allied product manufacturing"
	,"leisure"
	,"hospitality"
	,"lessors of nonfinancial intangible assets (except copyrighted works)"
	,"machinery manufacturing"
	,"management of companies"
	,"enterprises"
	,"manufacturing (naics 31-33)"
	,"merchant wholesalers"
	,"durable goods"
	,"merchant wholesalers"
	,"nondurable goods"
	,"mining (except oil"
	,"gas)"
	,"mining"
	,"quarrying"
	,"oil"
	,"gas extraction"
	,"miscellaneous manufacturing"
	,"miscellaneous store retailers"
	,"monetary authorities - central bank"
	,"motion picture"
	,"sound recording industries"
	,"motor vehicle"
	,"parts dealers"
	,"museums"
	,"historical sites"
	,"similar institutions"
	,"natural resources"
	,"mining"
	,"nonmetallic mineral product manufacturing"
	,"nonstore retailers"
	,"nursing"
	,"residential care facilities"
	,"oil"
	,"gas extraction"
	,"other information services"
	,"other services (except public administration)"
	,"paper manufacturing"
	,"performing arts"
	,"spectator sports"
	,"related industries"
	,"personal"
	,"laundry services"
	,"petroleum"
	,"coal products manufacturing"
	,"pipeline transportation"
	,"plastics"
	,"rubber products manufacturing"
	,"postal service"
	,"primary metal manufacturing"
	,"printing"
	,"related support activities"
	,"private households"
	,"professional"
	,"business services"
	,"professional"
	,"scientific"
	,"technical services"
	,"publishing industries (except internet)"
	,"rail transportation"
	,"real estate"
	,"real estate"
	,"rental"
	,"leasing"
	,"religious"
	,"grantmaking"
	,"civic"
	,"professional"
	,"similar organizations"
	,"rental"
	,"leasing services"
	,"repair"
	,"maintenance"
	,"retail trade"
	,"scenic"
	,"sightseeing transportation"
	,"securities"
	,"commodity contracts"
	,"other financial investments"
	,"related activities"
	,"service-providing industries"
	,"social assistance"
	,"specialty trade contractors"
	,"sporting goods"
	,"hobby"
	,"book"
	,"music stores"
	,"support activities for agriculture"
	,"forestry"
	,"support activities for mining"
	,"support activities for transportation"
	,"telecommunications"
	,"textile mills"
	,"textile product mills"
	,"trade"
	,"transportation"
	,"utilities"
	,"transit"
	,"ground passenger transportation"
	,"transportation equipment manufacturing"
	,"transportation"
	,"warehousing"
	,"truck transportation"
	,"utilities"
	,"warehousing"
	,"storage"
	,"waste management"
	,"remediation services"
	,"water transportation"
	,"wholesale electronic markets"
	,"agents"
	,"brokers"
	,"wholesale trade"
	,"wood product manufacturing"
	,"accommodations"
	,"accounting"
	,"advertising"
	,"aerospace"
	,"agriculture & agribusiness"
	,"air transportation"
	,"apparel & accessories"
	,"auto"
	,"banking"
	,"beauty & cosmetics"
	,"biotechnology"
	,"chemical"
	,"communications"
	,"computer"
	,"construction"
	,"consulting"
	,"consumer products"
	,"education"
	,"electronics"
	,"employment"
	,"energy"
	,"entertainment & recreation"
	,"fashion"
	,"financial services"
	,"food & beverage"
	,"health"
	,"information"
	,"information technology"
	,"insurance"
	,"journalism & news"
	,"legal services"
	,"manufacturing"
	,"media & broadcasting"
	,"medical devices & supplies"
	,"motion pictures & video"
	,"music"
	,"pharmaceutical"
	,"public administration"
	,"public relations"
	,"publishing"
	,"real estate"
	,"retail"
	,"service"
	,"sports"
	,"technology"
	,"telecommunications"
	,"tourism"
	,"transportation"
	,"travel"
	,"utilities"
	,"video game"
	,"web services"];
?>
