<?php
$actions = array(
	 "short"
	,"buy"
	,"sell"
	,"cover"
	,"hold"
	,"reduce"
	,"accumulate"
	,"strong sell"
	,"strong buy"
	,"avoid"
	,"sell, sell, sell"
	,"buy, buy, buy"
	,"buy or die"
	,"sell or go to hell"
	);

$markets = array(
	 "futures"
	,"equities"
	,"options"
	,"stocks"
	,"currencies"
	,"ETFs"
	,"warrants"
	,"bonds"
	);

$prediction_verbs = array(
	 "predict"
	,"anticipate"
	,"call"
	,"envision"
	,"forecast"
	,"forsee"
	,"conjecture"
	,"suppose"
	,"guess"
	,"infer"
	,"judge"
	,"portend"
	,"presume"
	,"surmise"
	,"prophecise"
	,"divine"
	,"prognosticate"
	,"apprehend"
	,"see"
	,"understand"
	,"percieve"
	,"expect"
	,"presage"
	,"espy"
	);

$predictions = array(
	 "rebound"
	,"crash"
	,"skyrocket"
	,"boom"
	,"bull pattern"
	,"bear pattern"
	,"bust"
	,"inflation"
	,"rise"
	,"fall"
	,"bullish butterfuly"
	,"cloud bank"
	,"downward channel"
	,"diamond top"
	,"diving board"
	,"domed house and three peaks"
	,"measured move down"
	,"ascending scallops"
	,"roof"
	,"pivot point"
	,"wolfe wave"
	,"wedge"
	,"Andrew" . u("2019") . "s pitchfork"
	,rand(0,20) . "th Elliot wave"
	,"support test"
	,"topping out"
	);
?>
